spring:
  application:
    name: gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/task-realm

  cloud:
    gateway:
      mvc:
        routes:
          # Auth Service
          - id: auth-app
            uri: http://localhost:8081
            predicates:
              - Path=/api/auth/**
            filters:
              - AddRequestHeader=X-Correlation-ID, gateway

              # Task Service
          - id: task-service-app
            uri: http://localhost:8082
            predicates:
              - Path=/api/tasks/**
            filters:
              - AddRequestHeader=X-Correlation-ID, gateway


server:
  port: 8090