spring:
  application:
    name: task-service-app

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/task-realm

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

  datasource:
    url: jdbc:postgresql://localhost:5433/task_postgres
    username: task
    password: task
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 8082

logging:
  level:
    org.hibernate.sql: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

task:
  scheduler:
    reminder-delay: 60000
    overdue-delay: 60000

